########
CRYPTO_LIB = tiny-AES128-C
SRC += aes.c aes-independant.c random_shift_rows.c
CDEFS += -DTINYAES128C
VPATH += :$(FIRMWAREPATH)/crypto5/$(CRYPTO_LIB)
EXTRAINCDIRS += $(FIRMWAREPATH)/crypto5/$(CRYPTO_LIB)
